# Create data directories
d /mnt/data/docker 0755 root root -
d /mnt/data/share 0755 root root -
d /mnt/data/ssl 0755 root root -
d /mnt/data/backup 0755 root root -
d /mnt/data/addons 0775 root root -
d /mnt/data/sos-logs 0755 root root -
